version: '2'
services:
  # Jenkins Master
  jenkins:
    image: blacklabelops/jenkins
    container_name: jenkins
    ports:
     - "8080:8080"
     - "50000"
    volumes_from:
      - volumes
    env_file:
      - jenkins-master.env
    labels:
      com.blacklabelops.description: "Jenkins Continuous Integration System"
      com.blacklabelops.service: "jenkins-master"

  # Jenkins Slave
  slave:
    image: ootaken/swarm-selenium
    links:
      - jenkins:jenkins
    env_file:
      - jenkins-slave.env
    labels:
      com.blacklabelops.description: "Jenkins Swarm JDK-8 Slave"
      com.blacklabelops.service: "slave"
      com.blacklabelops.applications: "java maven gradle"
